// advisor is a minimal MCP stdio server: it offers the consult_advisor tool to
// ZCode's main model (the executor), letting a stronger advisor model provide
// strategic advice. The advisor has a single backend: a cloud-hosted model on
// the local Ollama (billed through the Ollama account, not a local GGUF); the
// model and endpoint are hard-coded in the constants below — change them here
// and rebuild.
// Faithful to the spirit of Anthropic's advisor tool: when the advisor fails,
// degrade and let the task proceed; output is capped; timing is the main
// model's call. The protocol layer uses the official rmcp SDK; a consult's
// blocking work (rollout lookup + HTTP) runs via spawn_blocking and is
// serialized with Arc<Mutex> — mirroring the old hand-written loop's "one
// consult at a time" and preventing concurrent state-file writes (rmcp
// dispatches requests concurrently).

use std::sync::atomic::{AtomicI32, Ordering};
use std::sync::Arc;
use std::time::Duration;

use rmcp::{
    ErrorData as McpError,
    handler::server::wrapper::Parameters,
    model::*,
    schemars,
    tool, tool_handler, tool_router,
    ServerHandler, ServiceExt,
};

use crate::{hooks, http, logger, rollout};

pub const SERVER_NAME: &str = env!("CARGO_PKG_NAME"); // single source of truth: Cargo.toml
pub const SERVER_VERSION: &str = env!("CARGO_PKG_VERSION");
// Advisor model settings (single source of truth): kimi-k3:cloud is Ollama's
// cloud-hosted model; it needs `ollama login` first and a local `ollama serve`
// running; `ollama pull` can't fetch it and /api/tags doesn't list it. To
// change the model or endpoint, edit these two lines and rebuild.
pub const ADVISOR_MODEL: &str = "kimi-k3:cloud";
pub const ADVISOR_URL: &str = "http://localhost:11434/v1/chat/completions";

// Advisor output cap (kimi-k3 recommended value). A reasoning model's (kimi-k3
// and the like) thinking text counts toward max_tokens: a budget that's too
// small (e.g. 2048) burns out during reasoning and the body comes back empty;
// max_tokens is a cap, not a reservation — simple questions cost the same
pub const MAX_TOKENS: u64 = 131072;
pub const MAX_USES: i32 = 0; // per-session call cap for the MCP tool; 0 = unlimited

pub const ADVISOR_SYSTEM_PROMPT: &str = "You are a senior engineering advisor consulted by a coding agent mid-task. Answer with concise, actionable advice: key risks, recommended approach, and how to verify. Under 300 words. Do not restate the question. Plain text only.";

static USE_COUNT: AtomicI32 = AtomicI32::new(0); // MAX_USES counter (consults are serialized; atomic is illustrative)

// In-flight consult marker: if shutdown cuts a consult short after EOF,
// run_server leaves one stderr line so "why is there no advice this time" can
// be traced afterwards (degradation paths must not be fully silent)
static CONSULT_IN_FLIGHT: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);

struct InFlightGuard;
impl Drop for InFlightGuard {
    fn drop(&mut self) {
        CONSULT_IN_FLIGHT.store(false, Ordering::SeqCst);
    }
}

pub fn advisor_label() -> String {
    format!("{ADVISOR_MODEL} via Ollama")
}

#[derive(Clone)]
pub struct Advisor {
    // Arc ensures the same lock is shared even if rmcp clones the handler; the
    // whole consult (lookup → mark → HTTP) is serialized. (The tool router
    // holds no field: the call_tool/list_tools generated by #[tool_handler]
    // go through Self::tool_router() and rebuild the table; building it is
    // negligible.)
    consult_lock: Arc<tokio::sync::Mutex<()>>,
}

/// Field doc comments become the parameter descriptions (schemars); wording
/// kept verbatim from the old version.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ConsultArgs {
    /// What you want the advisor to decide or advise on.
    pub question: String,
    /// Optional supporting material: relevant code, error messages, or a summary of attempts so far.
    #[serde(default)]
    pub context: Option<String>,
}

#[tool_router]
impl Advisor {
    pub fn new() -> Self {
        Self {
            consult_lock: Arc::new(tokio::sync::Mutex::new(())),
        }
    }

    // description wording kept verbatim from the old version — it decides when
    // and how ZCode calls this tool
    #[tool(description = "Consult a stronger advisor model (kimi-k3:cloud via Ollama) for strategic guidance. Use it when starting a complex or unfamiliar task, before a large/risky change, when stuck after failed attempts, or when unsure about the approach. Your current conversation is attached automatically — focus the question on what you need decided, and use the optional context field only for material not yet in the conversation.")]
    async fn consult_advisor(
        &self,
        Parameters(ConsultArgs { question, context }): Parameters<ConsultArgs>,
    ) -> Result<CallToolResult, McpError> {
        if question.trim().is_empty() {
            logger::info("consult rejected reason=empty-question");
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "error: 'question' is required and must be non-empty",
            )]));
        }
        let context = context.unwrap_or_default();
        let _guard = self.consult_lock.lock().await;
        // rollout lookup (file scan) and HTTP (90s deadline) are both blocking
        // IO: hand them to the blocking pool instead of occupying runtime
        // threads; panics are caught via JoinError and degraded to a
        // caller-visible error result
        let res = tokio::task::spawn_blocking(move || consult(&question, &context)).await;
        Ok(res.unwrap_or_else(|e| {
            logger::info(&format!("consult failed reason=task-panic err={e}"));
            advice_error(&format!("error: consult task failed: {e}"))
        }))
    }
}

#[tool_handler]
impl ServerHandler for Advisor {
    // declare only the tools capability, no instructions — same capability
    // surface as the old version
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new(SERVER_NAME, SERVER_VERSION))
    }
}

pub fn run_server() {
    logger::init("server");
    eprintln!("advisor: model={ADVISOR_MODEL} url={ADVISOR_URL}"); // logging always goes to stderr; stdout carries only the MCP protocol
    logger::info(&format!(
        "server started version={SERVER_VERSION} model={ADVISOR_MODEL} url={ADVISOR_URL}"
    ));
    let rt = match tokio::runtime::Builder::new_current_thread().enable_all().build() {
        Ok(rt) => rt,
        Err(e) => {
            eprintln!("advisor: runtime init failed: {e}");
            logger::error(&format!("runtime init failed err={e}"));
            return;
        }
    };
    let result = rt.block_on(async {
        let service = Advisor::new().serve(rmcp::transport::stdio()).await?;
        service.waiting().await?;
        Ok::<(), Box<dyn std::error::Error + Send + Sync>>(())
    });
    // waiting() already includes rmcp's 5s drain window; give another 5s here
    // for leftover blocking consults to finish. Without it, dropping the
    // runtime would wait forever on an in-flight HTTP (up to the 90s deadline)
    // — the client is already gone, the response has nowhere to go; not worth
    // the wait. Ordering dependency: mark_consulted runs before the HTTP, so a
    // mid-flight cut leaves no half-written state file; if the state write ever
    // moves after the HTTP, this "safe cutoff" guarantee is void.
    rt.shutdown_timeout(Duration::from_secs(5));
    if CONSULT_IN_FLIGHT.load(Ordering::SeqCst) {
        eprintln!("advisor: shutdown cut an in-flight consult (client gone; state writes happen before HTTP, nothing half-written)");
        logger::info("shutdown cut an in-flight consult (client gone; state writes happen before HTTP, nothing half-written)");
    }
    if let Err(e) = result {
        eprintln!("advisor: server error: {e}");
        logger::error(&format!("server error err={e:?}"));
    }
}

// consult calls the advisor model (runs on a blocking thread). Any failure is
// returned as an is_error tool result (visible to the main model, which can
// carry on by itself); the server itself never dies — matching the original
// advisor's "an advisor failure must not fail the task" design.
fn consult(question: &str, context_str: &str) -> CallToolResult {
    let _in_flight = InFlightGuard;
    CONSULT_IN_FLIGHT.store(true, Ordering::SeqCst);
    let started = std::time::Instant::now();
    logger::info(&format!("consult question={:?}", crate::util::truncate(question, 48)));
    if MAX_USES > 0 && USE_COUNT.fetch_add(1, Ordering::SeqCst) + 1 > MAX_USES {
        logger::info("consult rejected reason=budget-exhausted");
        return advice_error(&format!(
            "error: advice budget exhausted (max {MAX_USES} consults for this session); proceed on your own"
        ));
    }
    // look up the calling session (UUID-level): automatically bring in that
    // session's conversation as advisor context
    let mut advice_context = context_str.to_string();
    let mut session_note = String::new();
    let mut matched_sess = String::from("-");
    if let Some(m) = rollout::find_calling_session(question) {
        eprintln!("advisor: rollout match: session={} file={}", m.session_id, m.path.display());
        logger::info(&format!("rollout match session={} file={}", m.session_id, m.path.display()));
        matched_sess.clone_from(&m.session_id);
        hooks::mark_consulted(&m.session_id); // consulted: the opening reminder goes quiet from now on
        if !m.dialog.is_empty() || !m.preamble.is_empty() {
            let mut b = String::new();
            if !m.preamble.is_empty() {
                // the current-turn monologue: the executor's thinking right
                // before asking; what the advisor should read first
                b.push_str(&format!("The agent's words immediately before calling you:\n{}\n\n", m.preamble));
            }
            if !m.dialog.is_empty() {
                b.push_str(&format!(
                    "The calling agent's current conversation (system prompt omitted, oldest first, may be truncated):\n{}",
                    m.dialog
                ));
            }
            if !context_str.trim().is_empty() {
                advice_context = format!("{b}\n--- additional context from the agent ---\n{context_str}");
            } else {
                advice_context = b;
            }
        }
        // the first 8 chars of the session id (sess_<uuid>) tag attribution;
        // from_utf8_lossy on non-ASCII mirrors the invalid-UTF-8 replacement
        let bytes = m.session_id.as_bytes();
        let short = if bytes.len() > 8 {
            String::from_utf8_lossy(&bytes[..8]).into_owned()
        } else {
            m.session_id.clone()
        };
        session_note = format!(" | session {short}");
    }
    // the content of "what the advisor saw" (full question, conversation,
    // advice) is preserved natively by ZCode's rollout files; the log records
    // only structural traces
    match ask_advisor(question, &advice_context) {
        Err(e) => {
            logger::info(&format!(
                "consult failed sess={matched_sess} t={:?} ctx={}B err={e}",
                started.elapsed(),
                advice_context.len()
            ));
            advice_error(&format!("error: {e}"))
        }
        Ok(advice) => {
            logger::info(&format!(
                "consult done sess={matched_sess} t={:?} ctx={}B advice={}B",
                started.elapsed(),
                advice_context.len(),
                advice.len()
            ));
            CallToolResult::success(vec![ContentBlock::text(format!(
                "[advisor · {}{session_note}]\n{advice}",
                advisor_label()
            ))])
        }
    }
}

// ask_advisor calls the local Ollama OpenAI-compatible endpoint. Shared by the
// MCP tool and hook mode; any error returns Err and the caller decides the
// presentation (MCP returns an is_error result, hooks pass through silently).
pub fn ask_advisor(question: &str, context_str: &str) -> Result<String, String> {
    let mut user_msg = question.to_string();
    if !context_str.trim().is_empty() {
        user_msg.push_str("\n\n--- context ---\n");
        user_msg.push_str(context_str);
    }
    let payload = serde_json::json!({
        "messages": [
            {"content": ADVISOR_SYSTEM_PROMPT, "role": "system"},
            {"content": user_msg, "role": "user"},
        ],
        "model": ADVISOR_MODEL,
        "max_tokens": MAX_TOKENS,
        "temperature": 0.3,
    });
    let body = serde_json::to_string(&payload).map_err(|e| format!("encode request: {e}"))?;

    let http::HttpResponse { status, body: resp_body } = http::post_json(ADVISOR_URL, &body, Duration::from_secs(90))
        .map_err(|e| format!("advisor API unreachable: {e}"))?;

    // decode the body before looking at the status — an error page (non-JSON)
    // lands in the unreadable-body path; the decoder takes only the first JSON
    // value and tolerates trailing data (json.Decoder semantics).
    let data = decode_advisor_body(&resp_body)
        .map_err(|e| format!("advisor API returned HTTP {status} with unreadable body: {e}"))?;

    if status != 200 {
        let mut msg = format!("HTTP {status}");
        if let Some(err) = &data.error {
            let m = err.message.as_deref().unwrap_or("");
            if !m.is_empty() {
                msg.push_str(&format!(": {m}"));
            }
        }
        return Err(format!("advisor API failed: {msg}"));
    }
    let choice = data.choices.and_then(|c| c.into_iter().next());
    let content = choice
        .as_ref()
        .and_then(|c| c.message.as_ref())
        .and_then(|m| m.content.as_deref())
        .unwrap_or("")
        .to_string();
    if !content.is_empty() {
        // finish=length with a non-empty body = a truncated answer: return it
        // as-is; the caller can't tell (acceptable — don't mistake it for
        // complete)
        return Ok(content);
    }
    if choice.as_ref().and_then(|c| c.finish_reason.as_deref()) == Some("length") {
        // a reasoning model's thinking counts toward max_tokens: length + an
        // empty body = the budget burned out during reasoning
        return Err(format!(
            "advisor spent all max_tokens={MAX_TOKENS} on reasoning before answering (finish_reason=length); raise the MAX_TOKENS constant in source and rebuild"
        ));
    }
    Err("advisor returned an empty response".into())
}

// Response from Ollama's OpenAI-compatible endpoint. Go's encoding/json treats
// JSON null as a no-op (the field keeps its zero value) while serde's default
// only covers "missing" — so every field takes Option to accept null and
// unwrap_or_default restores the zero-value semantics; this matters especially
// for finish_reason:null (common in OpenAI-compatible responses).
#[derive(serde::Deserialize, Default)]
struct AdvisorResp {
    #[serde(default)]
    choices: Option<Vec<Choice>>,
    #[serde(default)]
    error: Option<ErrorObj>,
}

#[derive(serde::Deserialize, Default)]
struct Choice {
    #[serde(default)]
    message: Option<Message>,
    #[serde(default)]
    finish_reason: Option<String>,
}

#[derive(serde::Deserialize, Default)]
struct Message {
    #[serde(default)]
    content: Option<String>,
}

#[derive(serde::Deserialize, Default)]
struct ErrorObj {
    #[serde(default)]
    message: Option<String>,
}

// decode_advisor_body: take only the first JSON value, tolerate trailing data;
// a top-level null maps back to zero values (Go semantics); an empty body
// (EOF) → Err, down the unreadable-body path.
fn decode_advisor_body(body: &[u8]) -> Result<AdvisorResp, String> {
    serde_json::Deserializer::from_slice(body)
        .into_iter::<Option<AdvisorResp>>()
        .next()
        .transpose()
        .map_err(|e| e.to_string())?
        .ok_or_else(|| "unexpected end of input".to_string())
        .map(|opt| opt.unwrap_or_default())
}

fn advice_error(msg: &str) -> CallToolResult {
    // rmcp's tool-level error: the caller (the main model) sees the content —
    // exactly the advisor degradation semantics
    CallToolResult::error(vec![ContentBlock::text(msg.to_string())])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tool_router_registers_consult_advisor() {
        let router = Advisor::tool_router();
        assert!(router.has_route("consult_advisor"));
        let tools = router.list_all();
        assert_eq!(tools.len(), 1);
        assert_eq!(tools[0].name.to_string(), "consult_advisor");
        let desc = tools[0].description.as_deref().unwrap_or("");
        assert!(desc.contains("kimi-k3:cloud via Ollama"), "{desc}");
        assert!(desc.contains("Your current conversation is attached automatically"), "{desc}");
    }

    #[test]
    fn advisor_body_decodes_null_semantics() {
        let d = decode_advisor_body(r#"{"choices":[{"message":{"content":"ok"},"finish_reason":null}]}"#.as_bytes()).unwrap();
        let choices = d.choices.unwrap();
        assert_eq!(
            choices.first().and_then(|c| c.message.as_ref()).and_then(|m| m.content.as_deref()),
            Some("ok")
        );
        let d = decode_advisor_body(r#"{"choices":[{"message":null,"finish_reason":null}],"error":null}"#.as_bytes()).unwrap();
        assert!(d.choices.unwrap()[0].message.is_none());
        let d = decode_advisor_body(b"null").unwrap();
        assert!(d.choices.is_none());
        assert!(decode_advisor_body(b"").is_err());
        assert!(decode_advisor_body(r#"{"choices":[{"message":{"content":42}}]}"#.as_bytes()).is_err());
        assert!(decode_advisor_body(b"{\"a\":1} trailing garbage").is_ok());
    }
}
